# Generated by Django 5.2.17 on 2026-09-27 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=16, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('window_seconds', models.FloatField(default=2.0)),
                ('windows_analysed', models.PositiveIntegerField(default=0)),
                ('device_label', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mic_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=16, unique=True)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('batch', 'Batch upload'), ('live', 'Live microphone')], default='upload', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_file', models.CharField(blank=True, max_length=255)),
                ('format', models.CharField(max_length=10)),
                ('file_size', models.PositiveBigIntegerField()),
                ('duration_s', models.FloatField()),
                ('sample_rate', models.PositiveIntegerField()),
                ('channels', models.PositiveSmallIntegerField()),
                ('bit_depth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('fingerprint', models.BinaryField(blank=True, null=True)),
                ('near_duplicate_score', models.FloatField(blank=True, null=True)),
                ('quality_grade', models.CharField(max_length=12)),
                ('quality_issues', models.JSONField(blank=True, default=list)),
                ('quality_metrics', models.JSONField(blank=True, default=dict)),
                ('reference_audio_id', models.CharField(blank=True, max_length=20)),
                ('reference_class', models.CharField(blank=True, max_length=40)),
                ('reference_split', models.CharField(blank=True, max_length=12)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exact_copies', to='events.audiorecord')),
                ('near_duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='near_copies', to='events.audiorecord')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audio_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='events.monitoringsession')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SoundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('segment_start_s', models.FloatField(default=0.0)),
                ('segment_end_s', models.FloatField(default=0.0)),
                ('processing_ms', models.FloatField(default=0.0)),
                ('python_model_version', models.CharField(max_length=60)),
                ('python_scores', models.JSONField(default=dict)),
                ('python_class', models.CharField(max_length=40)),
                ('python_confidence', models.FloatField()),
                ('python_margin', models.FloatField()),
                ('gtm_model_version', models.CharField(blank=True, max_length=60)),
                ('gtm_scores', models.JSONField(blank=True, null=True)),
                ('gtm_class', models.CharField(blank=True, max_length=40)),
                ('gtm_confidence', models.FloatField(blank=True, null=True)),
                ('gtm_margin', models.FloatField(blank=True, null=True)),
                ('gtm_error', models.CharField(blank=True, max_length=255)),
                ('class_match', models.BooleanField(default=False)),
                ('confidence_difference', models.FloatField(blank=True, null=True)),
                ('consistency', models.CharField(max_length=30)),
                ('windows', models.JSONField(blank=True, default=dict)),
                ('final_class', models.CharField(db_index=True, max_length=40)),
                ('confidence_level', models.CharField(max_length=10)),
                ('severity', models.CharField(choices=[('Informational', 'Informational'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], db_index=True, max_length=15)),
                ('alert_status', models.CharField(max_length=20)),
                ('recommended_action', models.TextField(blank=True)),
                ('review_required', models.BooleanField(db_index=True, default=False)),
                ('review_reasons', models.JSONField(blank=True, default=list)),
                ('overlapping_classes', models.JSONField(blank=True, default=list)),
                ('repeated_detections', models.PositiveIntegerField(default=1)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('Uploaded', 'Uploaded'), ('Classified', 'Classified'), ('Uncertain', 'Uncertain'), ('Alert Generated', 'Alert Generated'), ('Manual Review', 'Manual Review'), ('Reviewed', 'Reviewed'), ('Closed', 'Closed')], db_index=True, default='Classified', max_length=20)),
                ('reviewed_class', models.CharField(blank=True, max_length=40)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.audiorecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
