# Generated by Django 5.2.17 on 2026-09-28 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='soundevent',
            name='reviewed_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='soundevent',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soundevent',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soundevent',
            name='reviewed_severity',
            field=models.CharField(blank=True, choices=[('Informational', 'Informational'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=15),
        ),
        migrations.CreateModel(
            name='ReviewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('confirm', 'Confirmed the class'), ('correct', 'Corrected the class'), ('comment', 'Comment'), ('close', 'Closed'), ('reopen', 'Reopened')], max_length=10)),
                ('previous_class', models.CharField(blank=True, max_length=40)),
                ('new_class', models.CharField(blank=True, max_length=40)),
                ('severity', models.CharField(blank=True, max_length=15)),
                ('recommended_action', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.soundevent')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'review entries',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
