# Generated by Django 5.2.17 on 2026-09-27 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('critical', models.BooleanField(default=False)),
                ('alert', models.BooleanField(default=False, verbose_name='raises an alert')),
                ('severity', models.CharField(choices=[('Informational', 'Informational'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Informational', max_length=15)),
                ('alert_type', models.CharField(default='environment', max_length=20)),
                ('min_confidence', models.FloatField(default=0.5)),
                ('top_two_margin', models.FloatField(default=0.1)),
                ('consecutive_detections', models.PositiveSmallIntegerField(default=1)),
                ('require_model_agreement', models.BooleanField(default=False)),
                ('min_quality', models.CharField(choices=[('Good', 'Good'), ('Acceptable', 'Acceptable'), ('Poor', 'Poor')], default='Poor', max_length=12)),
                ('recommended_action', models.TextField(blank=True)),
                ('manual_review', models.TextField(blank=True, verbose_name='manual-review condition')),
                ('escalate_after_minutes', models.FloatField(blank=True, help_text='Unhandled alerts are escalated after this many minutes.', null=True)),
                ('raise_to_critical', models.JSONField(blank=True, null=True)),
                ('noise_limit_dbfs', models.FloatField(blank=True, null=True)),
                ('above_noise_limit', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-critical', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.CharField(max_length=40)),
                ('severity', models.CharField(db_index=True, max_length=15)),
                ('alert_type', models.CharField(max_length=20)),
                ('critical', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=255)),
                ('recommended_action', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('escalated', 'Escalated'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved')], db_index=True, default='active', max_length=15)),
                ('escalate_after_minutes', models.FloatField(blank=True, null=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='events.soundevent')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('created', 'Created'), ('acknowledged', 'Acknowledged'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated'), ('auto_escalated', 'Escalated automatically'), ('resolved', 'Resolved'), ('note', 'Note')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='alerts.alert')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_confidence', models.FloatField(default=0.5, help_text='Below this a result is Low confidence and goes to manual review.')),
                ('top_two_margin', models.FloatField(default=0.1, help_text='Minimum gap between the best and second-best class.')),
                ('weak_match_difference', models.FloatField(default=0.3, help_text='Same class but confidences differ by more than this: Weak Match.')),
                ('overlap_threshold', models.FloatField(default=0.25, help_text='Two event classes at or above this in one window: overlapping sounds.')),
                ('unknown_confidence', models.FloatField(default=0.35, help_text='Below this the sound is reported as Unknown.')),
                ('repeat_window_seconds', models.FloatField(default=10, help_text='Live: detections within this period count as repeated.')),
                ('live_window_seconds', models.FloatField(default=2.0, help_text='Length of each live-microphone window (1-3 s).')),
                ('max_upload_mb', models.PositiveIntegerField(default=25)),
                ('audio_retention_days', models.PositiveIntegerField(default=90, help_text='Stored audio older than this is deleted.')),
                ('event_retention_days', models.PositiveIntegerField(default=365, help_text='Event records older than this are deleted.')),
                ('store_live_audio', models.BooleanField(default=True, help_text='Keep audio of live windows that raise an alert or need review.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'decision settings',
            },
        ),
    ]
