# Generated by Django 5.2.17 on 2026-09-28 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertaction',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
