# Generated by Django 5.2.17 on 2026-09-28 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('failed_uploads', 'Repeated failed uploads'), ('model_failure', 'Model failure'), ('low_confidence', 'Unusual low-confidence spike'), ('critical_alerts', 'Excessive critical alerts'), ('duplicates', 'Duplicate files'), ('failed_logins', 'Failed login attempts')], max_length=20)),
                ('key', models.CharField(blank=True, max_length=150)),
                ('message', models.CharField(max_length=300)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
